### ISSUE TITLE
Sheet opens in preview as sheet above app instead of on the screenshot

### ISSUE THREAD

**Issue by roygroothulze** [goodwhale/AspirinShot#3]
My app has a sheet with a map below. In the screenshot only the map is visible but the sheet gets opened above the controls.

<img width="278" alt="image" src="https://github.com/goodwhale/AspirinShot/assets/45966542/59fa3964-53a2-40a1-b7fc-51db761eca90">

**Comment by sowenjub** [comment]
Hey, @roygroothulze, thanks for the feedback.

You need to use a ZStack with the map view and the sheet content. Due to the way it works, it's not currently possible to handle all controls or sheets presented onAppear for instance, so you have to recreate it.

I started to create components for some of the situations (eg: [ScreenshotInASheetView](https://github.com/goodwhale/AspirinShot/blob/main/StarterKit/ScreenshotInASheetView.swift)) and will see if I can make it easier in the future.

**Comment by roygroothulze** [comment]
Thank you for your help!

**Comment by sowenjub** [comment]
Of course, anytime 😊
